name: my first schedule workflow

on: 
  schedule:
    - cron: '*/1 * * * *'

jobs:
  my-first-schedule-workflow-job:
    runs-on: ubuntu-latest
    steps:
      - name: my-first-step
        run: echo "you did it, great scheduled job dude! date $(date)"
